name: norwegian_tech_assessment
description: Technical Assessment for Norwegian Cruise Lines
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  basic_utils: ^4.5.2
  http: ^0.13.5
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/norwegian_background.png
   - assets/waves_border.png
